### ISSUE TITLE
Important changes regarding absolute encoder arm

### ISSUE THREAD

**Issue by Node-Kid** [Dreadbot/Dreadbots2024#10]
To make sure that the arm functions properly and does not jerk on startup, this line needs to be changed to `absoluteEncoder.get()` to make sure that the current arm state is being set correctly
In Arm.java:
```java
 public void setArmStartState() {
        this.armState = new State(absoluteEncoder.get(), 0);
    }
```
Renable the line for seting the arm state with the correct position in RobotContainer.java:
```java
public void teleopInit() {
        arm.setReference(new State(arm.getEncoderPosition(), 0));
        arm.setArmStartState();
    }
```

**Comment by pantaelaman** [comment]
I just added the fix, should be good to run now.
