### ISSUE TITLE
Research timestamp issues in the PoseEstimator

### ISSUE THREAD

**Issue by pantaelaman** [Dreadbot/Dreadbots2024#11]
Currently, to add vision measurements to the estimator, we're just assuming that the measurements are current, since trying to add them with the timestamp was not working appropriately. While this works for now, it's kind of ugly, so I'd like to get the timestamp figured out. My guess is that either the units or reference time for the timestamp in the `SwerveDrivePoseEstimator` do not line up with those from the `BooleanSubscriber`.

Hopefully we can find a way to replace
```java
poseEstimator.resetPosition(
    getGyroRotation(),
    new SwerveModulePosition[] {
        frontLeftModule.getPosition(),
        frontRightModule.getPosition(),
        backLeftModule.getPosition(),
        backRightModule.getPosition(),
    },
    worldToRobot
);
```
with
```java
poseEstimator.addVisionMeasurement(worldToRobot, timestamp);
```
where timestamp is an accurately converted timestamp (preferably from `tagSeen.getLastChange()`).

**Comment by arman3412** [comment]
which file is this in?

**Comment by pantaelaman** [comment]
This works mostly, but occasionally when the odometry loses the vision measurements, it suddenly jumps off of where it should be. This behaviour seems to be somewhat dependent on the speed of the robot when losing the vision measurements.

**Comment by pantaelaman** [comment]
> which file is this in?

It's in `subsystems/Drive.java`
